### ISSUE TITLE
Sync local .bashrc file with Vagrant box

### ISSUE THREAD

**Issue by sboerrigter** [haroldangenent/box#3]
Sync local .bashrc file with Vagrant box, so you can use local bash settings like aliases.

**Comment by sboerrigter** [comment]
Maybe adding the aliases to the bin folder and syncing this folder is better so the .bashrc file on the VM doesn't get overwritten.

**Comment by haroldangenent** [comment]
Decided I won't be adding this to the box. I would recommend to sync a specific folder in the repo (say `bin/`) instead of a folder in your home directory.
